### PR TITLE
Adjust to upstream oslo.serialization namespace change

### PR DESCRIPTION
**Pull request by coreywright**
* oslo.serialization -> oslo_serialization

### CODE REVIEW

**Comment by coreywright** [comment]
the wafflehaus.nova tests are failing because wafflehaus is a requirement with it's own oslo namespace problems (see https://github.com/roaet/wafflehaus/pull/68).

```
  File "/home/travis/virtualenv/python2.7.9/src/wafflehaus/wafflehaus/base.py", line 17, in <module>
    from oslo.config import cfg
ImportError: No module named config
```

**Comment by coreywright** [comment]
amend the commit without any changes to trigger a travis-ci retest.

**Comment by coreywright** [comment]
tests passed on python2.7 but failed on python2.6 which doesn't surprise me as nova doesn't support python2.6 (or it could have been a dozen other dependencies that no longer support python2.6).

**Comment by roaet** [comment]
I AM SORRY OK :heart:

**Comment by roaet** [comment]
Merging because we dropped py26 support.

**Comment by coreywright** [comment]
@roaet thanks!

**Pull request merged**
